### ISSUE TITLE
WP 4.0 - extra 20px margin-left on #wpcontent

### ISSUE THREAD

**Issue by eliot-akira** [MachoThemes/wider-admin-menu#2]
Hello, I've been testing the latest beta version of WordPress, 4.0-RC1. I noticed that in _wp-admin/css/common.css_, there is a new line that adds `padding-left: 20px` on #wpcontent. This makes the left margin too big, as Wider Admin Menu adds an extra 20px already.

To keep the left margin the same after update to 4.0., I added the following on line 112 of _wider-admin-menu.php_:

`
if ( version_compare( $wp_version, '4.0', '>=' ) )
    $w2px =  $wpx;
else
    $w2px = ( $w + 20 ) . 'px';
`

In addition, to make _version_compare_ consider the beta version I'm using, I had to do:

`
if ( version_compare( $wp_version, '4.0-RC1', '>=' ) )
`

That's a bit awkward, and I wonder if it will correctly catch >=4.0..?

P.S. I just looked up [version_compare](http://php.net/manual/en/function.version-compare.php) in the PHP manual, and yes, the above should catch all versions including beta correctly.

**Comment by razvanaldea89** [comment]
Closing this as it is very old.
